test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET: 	YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY:	'pk_test_ED7ecSKdLp7WLb9h4jXsrLow'
  STRIPE_SECRET_KEY: 	'sk_test_fDhYy9P69RuRxQxmzy0OOYn1'
development:
  <<: *default
